import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { checkout } from "../checkout";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Physical NFTs</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Buy my physical NFTs</h1>
        <div className={styles.grid}>
          <div>
            <Image
              src="/images/monkeyreal.jpg"
              alt="monkey"
              width={240}
              height={240}
            />
            <p className={inter.className}>Very expensive art piece 1</p>
            <button
              onClick={() => {
                checkout({
                  lineItems: [
                    {
                      price: "price_1MKiCqFV6wNXacUdiOlaGq8H",
                      quantity: 1,
                    },
                  ],
                });
              }}
            >
              BUY!
            </button>
          </div>

          <div>
            <Image
              src="/images/monyek1.jpg"
              alt="monkeynft"
              width={240}
              height={240}
            />
            <p className={inter.className}>Very expensive art piece 2</p>
          </div>
        </div>
      </main>
    </>
  );
}
